import { PEOPLE_INFORMATION_TYPE } from "types/people/people-information";

export const PEOPLE_ITEMS = {
  TEN: 10,
};

export enum DEPARTMENT {
  MEDIA = "미디어학부",
  BUSINESS = "경영학과",
  BIO_MEDICAL_ENGINEERING = "바이오의공학부",
  BIOLOGICAL_ENGINEERING = "생명공학부",
  EDUCATION = "교육학과",
  HEALTH_ENVIRONMENTAL_CONVERGENCE_SCIENCE = "보건환경융합과학부",
  DESIGN = "디자인조형학부",
  KOREA_LANGUAGE_AND_LITERATURE = "국어국문학과",
  COMPUTER = "컴퓨터학과",
  JAPANESE_LANGUAGE_AND_LITERATURE = "일어일문학과",
  RUSSIAN_LANGUAGE_AND_LITERATURE = "노어노문학과",
  STATISTICS = "통계학과",
  ELECTRONIC_ELECTRICAL_ENGINEERING = "전기전자공학부",
  SOCIOLOGY = "사회학과",
  PSYCHOTHERAPY = "심리학과",
  EARTH_ENVIRONMENTAL_SCIENCE = "지구환경과학부",
  ENGLISH_EDUCATION = "영어교육학과",
}

export enum MANAGEMENT_TEAM_POSITION {
  REPRESENTATICE = "대표",
  EXECUTIVE = "임원진",
  EDUCATION = "학술부",
  PROJECT_MANAGER = "기획부",
  NORMAL = "",
}

export const PEOPLE_INFORMATION: PEOPLE_INFORMATION_TYPE[] = [
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "김나영",
    department: DEPARTMENT.MEDIA,
    classOf: 20,
    imgSrc: "/images/profile/10기_김나영.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "김민지",
    department: DEPARTMENT.MEDIA,
    classOf: 18,
    imgSrc: "/images/profile/10기_김민지.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "김지욱",
    department: DEPARTMENT.BUSINESS,
    classOf: 17,
    imgSrc: "/images/profile/10기_김지욱.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "김채현",
    department: DEPARTMENT.BIO_MEDICAL_ENGINEERING,
    classOf: 20,
    imgSrc: "/images/profile/10기_김채현.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "김하경",
    department: DEPARTMENT.BIOLOGICAL_ENGINEERING,
    classOf: 19,
    imgSrc: "/images/profile/10기_김하경.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.REPRESENTATICE,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "문지후",
    department: DEPARTMENT.EDUCATION,
    classOf: 20,
    imgSrc: "/images/profile/10기_문지후.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "박견우",
    department: DEPARTMENT.HEALTH_ENVIRONMENTAL_CONVERGENCE_SCIENCE,
    classOf: 18,
    imgSrc: "/images/profile/10기_박견우.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "박소정",
    department: DEPARTMENT.DESIGN,
    classOf: 19,
    imgSrc: "/images/profile/10기_박소정.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "백민기",
    department: DEPARTMENT.KOREA_LANGUAGE_AND_LITERATURE,
    classOf: 17,
    imgSrc: "/images/profile/10기_백민기.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "손수원",
    department: DEPARTMENT.COMPUTER,
    classOf: 19,
    imgSrc: "/images/profile/10기_손수원.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "송명훈",
    department: DEPARTMENT.COMPUTER,
    classOf: 19,
    imgSrc: "/images/profile/10기_송명훈.png",
    secondMajor: "자전",
    managementTeam: MANAGEMENT_TEAM_POSITION.EXECUTIVE,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "양휘민",
    department: DEPARTMENT.JAPANESE_LANGUAGE_AND_LITERATURE,
    classOf: 20,
    imgSrc: "/images/profile/10기_양휘민.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "엄혜영",
    department: DEPARTMENT.HEALTH_ENVIRONMENTAL_CONVERGENCE_SCIENCE,
    classOf: 19,
    imgSrc: "/images/profile/10기_엄혜영.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.PROJECT_MANAGER,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "운정윤",
    department: DEPARTMENT.RUSSIAN_LANGUAGE_AND_LITERATURE,
    classOf: 18,
    imgSrc: "/images/profile/10기_윤정윤.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.EXECUTIVE,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "이소희",
    department: DEPARTMENT.STATISTICS,
    classOf: 20,
    imgSrc: "/images/profile/10기_이소희.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "이영서",
    department: DEPARTMENT.BUSINESS,
    classOf: 21,
    imgSrc: "/images/profile/10기_이영서.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.PROJECT_MANAGER,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "이예원",
    department: DEPARTMENT.ELECTRONIC_ELECTRICAL_ENGINEERING,
    classOf: 19,
    imgSrc: "/images/profile/10기_이예원.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "이유진",
    department: DEPARTMENT.SOCIOLOGY,
    classOf: 18,
    imgSrc: "/images/profile/10기_이유진.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "이지수",
    department: DEPARTMENT.MEDIA,
    classOf: 19,
    imgSrc: "/images/profile/10기_이지수.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "이지은",
    department: DEPARTMENT.PSYCHOTHERAPY,
    classOf: 20,
    imgSrc: "/images/profile/10기_이지은.png",
    masterDegree: "석사",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "전민철",
    department: DEPARTMENT.BUSINESS,
    classOf: 17,
    imgSrc: "/images/profile/10기_전민철.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "전성운",
    department: DEPARTMENT.ELECTRONIC_ELECTRICAL_ENGINEERING,
    classOf: 22,
    imgSrc: "/images/profile/10기_전성운.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.EDUCATION,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "정지우",
    department: DEPARTMENT.BUSINESS,
    classOf: 20,
    imgSrc: "/images/profile/10기_정지우.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.EXECUTIVE,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "주장규",
    department: DEPARTMENT.PSYCHOTHERAPY,
    classOf: 21,
    imgSrc: "/images/profile/10기_주장규.png",
    masterDegree: "석사",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "차수지",
    department: DEPARTMENT.EARTH_ENVIRONMENTAL_SCIENCE,
    classOf: 18,
    imgSrc: "/images/profile/10기_차수지.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "한성수",
    department: DEPARTMENT.KOREA_LANGUAGE_AND_LITERATURE,
    classOf: 17,
    imgSrc: "/images/profile/10기_한성수.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "한예진",
    department: DEPARTMENT.KOREA_LANGUAGE_AND_LITERATURE,
    classOf: 21,
    imgSrc: "/images/profile/10기_한예진.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.NORMAL,
  },
  {
    gen: PEOPLE_ITEMS.TEN,
    name: "홍세린",
    department: DEPARTMENT.ENGLISH_EDUCATION,
    classOf: 18,
    imgSrc: "/images/profile/10기_홍세린.png",
    managementTeam: MANAGEMENT_TEAM_POSITION.PROJECT_MANAGER,
  },
];
