export const ABOUT_ITEMS = {
  INTRODUCTION: "Introduction",
  GREETING: "Greeting",
  HISTORY: "History",
  ACHIEVEMENT: "Achievement",
  PARTNERS: "Partners",
};

export const ABOUT_HISTORY = [
  { YEAR: "2022", 
    TITLE:"NEXT x Likelion 10기", 
    CONTENT: ["점술 상담 중개 플랫폼 ‘천명’ 시리즈A 투자 유치", "Web3 어플리케이션 스튜디오 ‘메셔’ 이더리움 글로벌 해커톤 우승", "디지털 굿즈 올인원 플랫폼 ‘하플’ 시드 투자 유치", "감성 숙소 큐레이션 ‘하우' 도전 k-스타트업 2021 왕중왕전 최연소 장관상 수상 & 시드 투자 유치", "원클린, 클링 등의 서비스 창업 경진대회 출품 및 수상",],
    IsAlumni: 1,
    IsActing: 1,
  },
  { YEAR: "2021", 
    TITLE: "NEXT x Likelion 9기",
    CONTENT: ["고려대 수강신청 알리미 리뉴얼", "하플, 돈키, 연고링 서비스 출시", "삼성전자, 네이버, 카카오, 배달의 민족 등 개발자, PM, 마케터 다수 배출"],
    IsAlumni: 0,
    IsActing: 0,
  },
  { YEAR: "2020", 
    TITLE: "NEXT x Likelion 8기",
    CONTENT: ["고려대 수강신청 알리미 서비스 출시", "네이버, 삼성 SDS, LG CNS, 뱅크샐러드 등 개발직군 취업 多",],
    IsAlumni: 0,
    IsActing: 0,
  },
  { YEAR: "2019", 
    TITLE: "NEXT x Likelion 7기",
    CONTENT: ["루비 온 레일즈 -> 장고 기반 세션으로 전환", "코로나 알리미 MAU 300만/마스크 알리미 MAU 2000만 돌파 및 각종 언론 인터뷰",],
    IsAlumni: 0,
    IsActing: 0,
  },
  { YEAR: "2018", 
    TITLE: "고려대 경영대학 소속 소프트웨어벤처 학회 “NEXT” 출범",
    CONTENT: ["인문 캠퍼스 최초 소프트웨어 학회 설립",  "웹 프로그래밍 교육 자체 진행 및 스타트업 창업 교육 병행",],
    IsAlumni: 0,
    IsActing: 0,
  },
  { YEAR: "2015-2017", 
    TITLE: "고려대 멋쟁이사자처럼 3 - 5기 활동",
    CONTENT: ["연합동아리의 고려대학교 지부로서 기초 웹 프로그래밍 교육 진행",],
    IsAlumni: 0,
    IsActing: 0,
  },
  { YEAR: "2014", 
    TITLE: "고려대 멋쟁이사자처럼(2기) 시작",
    CONTENT: ["연비전공자에게 컴퓨터 프로그래밍을 가르쳐주는 동아리로서 2013년도 서울대 1기 시범 운영 후, 서울권 주요 대학으로 확장",],
    IsAlumni: 0,
    IsActing: 0,
  },
];